---
swagger: "2.0"
info:
  description: "ATTX Provenance Service for constructing and retrieving data provenance."
  version: "0.1"
  title: "ATTX Provenance Service"
  contact:
    name: "ATTX project"
    url: "https://www.helsinki.fi/en/projects/attx-2016"
  license:
    name: "MIT"
basePath: "/"
tags:
- name: "ProvService"
  description: "Provenance service core functionalities"
  externalDocs:
    description: "just use it"
    url: "https://attx-project.github.io/"
- name: "ProvGraph"
  description: "Graph interface for Provenance Service"
  externalDocs:
    description: "just use it"
    url: "https://attx-project.github.io/"
schemes:
- "http"
paths:
  /health:
    get:
      description: "Get health of Provenance Service."
      responses:
        200:
          description: "Successful response."
  /{apiversion}/prov:
    post:
      tags:
      - "ProvService"
      description: "Construct Provenance based on request."
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - in: "body"
        name: "prov request"
        required: true
        schema:
          $ref: "#/definitions/Prov"
      responses:
        202:
          description: "Accepted."
          schema:
            $ref: "#/definitions/ProvStatus"
        400:
          description: "Invalid Input."
  /{apiversion}/prov/show/{entityID}:
    get:
      tags:
      - "ProvService"
      description: "Show a specific Provenance based on Activity ID."
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - name: "entityID"
        in: "path"
        description: "Fetch Provenance related information for an entity"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful response."
        410:
          description: "No Provenace information for entity available."
  /{apiversion}/graph/query:
    post:
      tags:
      - "ProvGraph"
      operationId: "graph_query"
      description: "Send a SPARQL query to the Graph Store"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - in: "body"
        name: "linking"
        required: true
        schema:
          $ref: "#/definitions/Query"
      responses:
        200:
          description: "Accepted."
        400:
          description: "Invalid Input."
  /{apiversion}/graph/update:
    post:
      tags:
      - "ProvGraph"
      operationId: "graph_update"
      description: "Send an update query to the Graph Store."
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - in: "body"
        name: "linking"
        required: true
        schema:
          $ref: "#/definitions/Update"
      responses:
        200:
          description: "Accepted."
        400:
          description: "Invalid Input."
  /{apiversion}/graph/list:
    get:
      tags:
      - "ProvGraph"
      description: "Get list of Graphs."
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful response."
          schema:
            type: "object"
        410:
          description: "No Graphs available."
  /{apiversion}/graph/statistics:
    get:
      tags:
      - "ProvGraph"
      description: "Get statistics related to the Dataset."
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful response."
          schema:
            type: "object"
        410:
          description: "Statistics Unavailable."
  /{apiversion}/graph:
    get:
      tags:
      - "ProvGraph"
      description: "Get a named graph triples."
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - name: "uri"
        in: "query"
        description: "The named graph ID; must be a URI."
        required: true
        type: "string"
        format: "int64"
      responses:
        200:
          description: "Successful response."
          schema:
            type: "object"
        410:
          description: "Graph does not exist."
    delete:
      tags:
      - "ProvGraph"
      description: "Delete graph with a certain ID."
      parameters:
      - name: "uri"
        in: "query"
        description: "The named graph ID; must be a URI."
        required: true
        type: "string"
        format: "int64"
      responses:
        200:
          description: "OK"
definitions:
  Prov:
    required:
    - "id"
    - "type"
    properties:
      id:
        type: "integer"
        format: "int64"
      type:
        type: "string"
      properties:
        type: "object"
        properties: {}
  ProvStatus:
    required:
    - "id"
    - "status"
    properties:
      id:
        type: "integer"
        format: "int64"
      status:
        type: "string"
  Query:
    required:
    - "namedGraph"
    - "query"
    properties:
      namedGraph:
        type: "string"
      query:
        type: "string"
  Update:
    required:
    - "namedGraph"
    - "triples"
    properties:
      namedGraph:
        type: "string"
      triples:
        type: "string"
